create table if not exists public.gallery_items (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  extension text not null default 'mov' check (extension in ('mov', 'mp4', 'webm')),
  width integer not null check (width > 0),
  height integer not null check (height > 0),
  title text not null,
  client text not null,
  type text not null,
  year text not null,
  status text not null default 'processing' check (status in ('processing', 'published', 'failed', 'archived')),
  sort_order integer not null default 0,
  processing_error text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists gallery_items_public_order
  on public.gallery_items (status, sort_order, created_at);

alter table public.gallery_items enable row level security;

create policy "Published gallery items are public"
  on public.gallery_items for select
  using (status = 'published');

create or replace function public.set_gallery_item_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists gallery_items_updated_at on public.gallery_items;
create trigger gallery_items_updated_at
  before update on public.gallery_items
  for each row execute function public.set_gallery_item_updated_at();